spring:
  main:
    banner-mode: "off"
  application:
    name: keycloak-springboot-oauth2
server:
  port: 8181
 
#logging.level.org.keycloak: trace
#logging.level.org.springframework.security: trace

security:
  basic:
    enabled: false                    # again no basic auth 
  oauth2:
    client:
      clientId: client1          # the client scope (the resource in the secured service)
      clientSecret: 552b0f67-8f11-48ce-964a-9b4471af88a1   # copy this secret key from your keycloak admin console in the client configuration
      accessTokenUri: http://localhost:8080/auth/realms/bookstore/protocol/openid-connect/token   # these uris are defined in the openId-connect protocol
      userAuthorizationUri: http://localhost:8080/auth/realms/bookstore/protocol/openid-connect/auth
    resource:
      userInfoUri: http://localhost:8080/auth/realms/bookstore/protocol/openid-connect/userinfo
 
