spring:
  main:
    banner-mode: "off"
  application:
    name: keycloak-springboot-oauth2
server:
  port: 8080
 
logging.level.org.keycloak: trace
logging.level.org.springframework.security: trace
 
keycloak:
  enable-basic-auth: false  # basic auth is default true, we dont want that
  realm: demo-realm   # our keycloak realm this ressource service should be based in
  auth-server-url: http://localhost:8280/auth  # the url to our sso server (keycloak)
  ssl-required: external  # no ssl is ok for demo  - do not use this in production 
  resource: demo-client  # the realm-client which accessing clients should be authenticate with 
  use-resource-role-mappings: true # use this if you manage your roles in client scope not in realm scope
  public-client: false # we do not write a web-app - so no login page and redirects are necessary
  bearer-only: true  # authentification via accesstoken is fine
  securityConstraints:
  -   authRoles:
      - demo-user-role   # the authenticated user needs this role to be authorized to access this ressource
      securityCollections:
      -   name: acces only with auth # just a comment
          patterns:
          - /message  # the actual rest endpoint which shoulb be protected